<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateOsuCountryTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('osu_country', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->integer('id')->unique();
            $table->primary('id');
            $table->string('name');
            $table->string('code');
        });

        DB::table('osu_country')->insert([
            ['id' => 0, 'name' => 'Unknown',  'code' => ''],
            ['id' => 1, 'name' => 'Oceania',  'code' => ''],
            ['id' => 2, 'name' => 'Europe',  'code' => ''],
            ['id' => 3, 'name' => 'Andorra',  'code' => 'AD'],
            ['id' => 4, 'name' => 'UAE',  'code' => 'AE'],
            ['id' => 5, 'name' => 'Afghanistan',  'code' => 'AF'],
            ['id' => 6, 'name' => 'Antigua',  'code' => 'AG'],
            ['id' => 7, 'name' => 'Anguilla',  'code' => 'AI'],
            ['id' => 8, 'name' => 'Albania',  'code' => 'AL'],
            ['id' => 9, 'name' => 'Armenia',  'code' => 'AM'],
            ['id' => 10, 'name' => 'Netherlands Antilles',  'code' => 'NL'],
            ['id' => 11, 'name' => 'Angola',  'code' => 'AO'],
            ['id' => 12, 'name' => 'Antarctica',  'code' => ''],
            ['id' => 13, 'name' => 'Argentina',  'code' => ''],
            ['id' => 14, 'name' => 'American Samoa',  'code' => ''],
            ['id' => 15, 'name' => 'Austria',  'code' => ''],
            ['id' => 16, 'name' => 'Australia',  'code' => ''],
            ['id' => 17, 'name' => 'Aruba',  'code' => ''],
            ['id' => 18, 'name' => 'Azerbaijan',  'code' => ''],
            ['id' => 19, 'name' => 'Bosnia',  'code' => ''],
            ['id' => 20, 'name' => 'Barbados',  'code' => ''],
            ['id' => 21, 'name' => 'Bangladesh',  'code' => ''],
            ['id' => 22, 'name' => 'Belgium',  'code' => ''],
            ['id' => 23, 'name' => 'Burkina Faso',  'code' => ''],
            ['id' => 24, 'name' => 'Bulgaria',  'code' => ''],
            ['id' => 25, 'name' => 'Bahrain',  'code' => ''],
            ['id' => 26, 'name' => 'Burundi',  'code' => ''],
            ['id' => 27, 'name' => 'Benin',  'code' => ''],
            ['id' => 28, 'name' => 'Bermuda',  'code' => ''],
            ['id' => 29, 'name' => 'Brunei Darussalam',  'code' => ''],
            ['id' => 30, 'name' => 'Bolivia',  'code' => ''],
            ['id' => 31, 'name' => 'Brazil',  'code' => ''],
            ['id' => 32, 'name' => 'Bahamas',  'code' => ''],
            ['id' => 33, 'name' => 'Bhutan',  'code' => ''],
            ['id' => 34, 'name' => 'Bouvet Island',  'code' => ''],
            ['id' => 35, 'name' => 'Botswana',  'code' => ''],
            ['id' => 36, 'name' => 'Belarus',  'code' => ''],
            ['id' => 37, 'name' => 'Belize',  'code' => ''],
            ['id' => 38, 'name' => 'Canada',  'code' => ''],
            ['id' => 39, 'name' => 'Cocos Islands',  'code' => ''],
            ['id' => 40, 'name' => 'Congo',  'code' => ''],
            ['id' => 41, 'name' => 'Central African Republic',  'code' => ''],
            ['id' => 42, 'name' => 'Congo',  'code' => ''],
            ['id' => 43, 'name' => 'Switzerland',  'code' => ''],
            ['id' => 44, 'name' => 'Cote D\'Ivoire',  'code' => ''],
            ['id' => 45, 'name' => 'Cook Islands',  'code' => ''],
            ['id' => 46, 'name' => 'Chile',  'code' => ''],
            ['id' => 47, 'name' => 'Cameroon',  'code' => ''],
            ['id' => 48, 'name' => 'China',  'code' => ''],
            ['id' => 49, 'name' => 'Colombia',  'code' => ''],
            ['id' => 50, 'name' => 'Costa Rica',  'code' => ''],
            ['id' => 51, 'name' => 'Cuba',  'code' => ''],
            ['id' => 52, 'name' => 'Cape Verde',  'code' => ''],
            ['id' => 53, 'name' => 'Christmas Island',  'code' => ''],
            ['id' => 54, 'name' => 'Cyprus',  'code' => ''],
            ['id' => 55, 'name' => 'Czech Republic',  'code' => ''],
            ['id' => 56, 'name' => 'Germany',  'code' => ''],
            ['id' => 57, 'name' => 'Djibouti',  'code' => ''],
            ['id' => 58, 'name' => 'Denmark',  'code' => ''],
            ['id' => 59, 'name' => 'Dominica',  'code' => ''],
            ['id' => 60, 'name' => 'Dominican Republic',  'code' => ''],
            ['id' => 61, 'name' => 'Algeria',  'code' => ''],
            ['id' => 62, 'name' => 'Ecuador',  'code' => ''],
            ['id' => 63, 'name' => 'Estonia',  'code' => ''],
            ['id' => 64, 'name' => 'Egypt',  'code' => ''],
            ['id' => 65, 'name' => 'Western Sahara',  'code' => ''],
            ['id' => 66, 'name' => 'Eritrea',  'code' => ''],
            ['id' => 67, 'name' => 'Spain',  'code' => ''],
            ['id' => 68, 'name' => 'Ethiopia',  'code' => ''],
            ['id' => 69, 'name' => 'Finland',  'code' => ''],
            ['id' => 70, 'name' => 'Fiji',  'code' => ''],
            ['id' => 71, 'name' => 'Falkland Islands',  'code' => ''],
            ['id' => 72, 'name' => 'Micronesia, Federated States of',  'code' => ''],
            ['id' => 73, 'name' => 'Faroe Islands',  'code' => ''],
            ['id' => 74, 'name' => 'France',  'code' => ''],
            ['id' => 75, 'name' => 'France, Metropolitan',  'code' => ''],
            ['id' => 76, 'name' => 'Gabon',  'code' => ''],
            ['id' => 77, 'name' => 'United Kingdom',  'code' => ''],
            ['id' => 78, 'name' => 'Grenada',  'code' => ''],
            ['id' => 79, 'name' => 'Georgia',  'code' => ''],
            ['id' => 80, 'name' => 'French Guiana',  'code' => ''],
            ['id' => 81, 'name' => 'Ghana',  'code' => ''],
            ['id' => 82, 'name' => 'Gibraltar',  'code' => ''],
            ['id' => 83, 'name' => 'Greenland',  'code' => ''],
            ['id' => 84, 'name' => 'Gambia',  'code' => ''],
            ['id' => 85, 'name' => 'Guinea',  'code' => ''],
            ['id' => 86, 'name' => 'Guadeloupe',  'code' => ''],
            ['id' => 87, 'name' => 'Equatorial Guinea',  'code' => ''],
            ['id' => 88, 'name' => 'Greece',  'code' => ''],
            ['id' => 89, 'name' => 'South Georgia',  'code' => ''],
            ['id' => 90, 'name' => 'Guatemala',  'code' => ''],
            ['id' => 91, 'name' => 'Guam',  'code' => ''],
            ['id' => 92, 'name' => 'Guinea-Bissau',  'code' => ''],
            ['id' => 93, 'name' => 'Guyana',  'code' => ''],
            ['id' => 94, 'name' => 'Hong Kong',  'code' => ''],
            ['id' => 95, 'name' => 'Heard Island',  'code' => ''],
            ['id' => 96, 'name' => 'Honduras',  'code' => ''],
            ['id' => 97, 'name' => 'Croatia',  'code' => ''],
            ['id' => 98, 'name' => 'Haiti',  'code' => ''],
            ['id' => 99, 'name' => 'Hungary',  'code' => ''],
            ['id' => 100, 'name' => 'Indonesia',  'code' => ''],
            ['id' => 101, 'name' => 'Ireland',  'code' => ''],
            ['id' => 102, 'name' => 'Israel',  'code' => ''],
            ['id' => 103, 'name' => 'India',  'code' => ''],
            ['id' => 104, 'name' => 'British Indian Ocean Territory',  'code' => ''],
            ['id' => 105, 'name' => 'Iraq',  'code' => ''],
            ['id' => 106, 'name' => 'Iran, Islamic Republic of',  'code' => ''],
            ['id' => 107, 'name' => 'Iceland',  'code' => ''],
            ['id' => 108, 'name' => 'Italy',  'code' => ''],
            ['id' => 109, 'name' => 'Jamaica',  'code' => ''],
            ['id' => 110, 'name' => 'Jordan',  'code' => ''],
            ['id' => 111, 'name' => 'Japan',  'code' => ''],
            ['id' => 112, 'name' => 'Kenya',  'code' => ''],
            ['id' => 113, 'name' => 'Kyrgyzstan',  'code' => ''],
            ['id' => 114, 'name' => 'Cambodia',  'code' => ''],
            ['id' => 115, 'name' => 'Kiribati',  'code' => ''],
            ['id' => 116, 'name' => 'Comoros',  'code' => ''],
            ['id' => 117, 'name' => 'St. Kitts and Nevis',  'code' => ''],
            ['id' => 118, 'name' => 'Korea, Democratic People\'s Republic of',  'code' => ''],
            ['id' => 119, 'name' => 'Korea',  'code' => ''],
            ['id' => 120, 'name' => 'Kuwait',  'code' => ''],
            ['id' => 121, 'name' => 'Cayman Islands',  'code' => ''],
            ['id' => 122, 'name' => 'Kazakhstan',  'code' => ''],
            ['id' => 123, 'name' => 'Lao',  'code' => ''],
            ['id' => 124, 'name' => 'Lebanon',  'code' => ''],
            ['id' => 125, 'name' => 'St. Lucia',  'code' => ''],
            ['id' => 126, 'name' => 'Liechtenstein',  'code' => ''],
            ['id' => 127, 'name' => 'Sri Lanka',  'code' => ''],
            ['id' => 128, 'name' => 'Liberia',  'code' => ''],
            ['id' => 129, 'name' => 'Lesotho',  'code' => ''],
            ['id' => 130, 'name' => 'Lithuania',  'code' => ''],
            ['id' => 131, 'name' => 'Luxembourg',  'code' => ''],
            ['id' => 132, 'name' => 'Latvia',  'code' => ''],
            ['id' => 133, 'name' => 'Libyan Arab Jamahiriya',  'code' => ''],
            ['id' => 134, 'name' => 'Morocco',  'code' => ''],
            ['id' => 135, 'name' => 'Monaco',  'code' => ''],
            ['id' => 136, 'name' => 'Moldova, Republic of',  'code' => ''],
            ['id' => 137, 'name' => 'Madagascar',  'code' => ''],
            ['id' => 138, 'name' => 'Marshall Islands',  'code' => ''],
            ['id' => 139, 'name' => 'Macedonia, the Former Yugoslav Republic of',  'code' => ''],
            ['id' => 140, 'name' => 'Mali',  'code' => ''],
            ['id' => 141, 'name' => 'Myanmar',  'code' => ''],
            ['id' => 142, 'name' => 'Mongolia',  'code' => ''],
            ['id' => 143, 'name' => 'Macau',  'code' => ''],
            ['id' => 144, 'name' => 'Northern Mariana Islands',  'code' => ''],
            ['id' => 145, 'name' => 'Martinique',  'code' => ''],
            ['id' => 146, 'name' => 'Mauritania',  'code' => ''],
            ['id' => 147, 'name' => 'Montserrat',  'code' => ''],
            ['id' => 148, 'name' => 'Malta',  'code' => ''],
            ['id' => 149, 'name' => 'Mauritius',  'code' => ''],
            ['id' => 150, 'name' => 'Maldives',  'code' => ''],
            ['id' => 151, 'name' => 'Malawi',  'code' => ''],
            ['id' => 152, 'name' => 'Mexico',  'code' => ''],
            ['id' => 153, 'name' => 'Malaysia',  'code' => ''],
            ['id' => 154, 'name' => 'Mozambique',  'code' => ''],
            ['id' => 155, 'name' => 'Namibia',  'code' => ''],
            ['id' => 156, 'name' => 'New Caledonia',  'code' => ''],
            ['id' => 157, 'name' => 'Niger',  'code' => ''],
            ['id' => 158, 'name' => 'Norfolk Island',  'code' => ''],
            ['id' => 159, 'name' => 'Nigeria',  'code' => ''],
            ['id' => 160, 'name' => 'Nicaragua',  'code' => ''],
            ['id' => 161, 'name' => 'Netherlands',  'code' => ''],
            ['id' => 162, 'name' => 'Norway',  'code' => ''],
            ['id' => 163, 'name' => 'Nepal',  'code' => ''],
            ['id' => 164, 'name' => 'Nauru',  'code' => ''],
            ['id' => 165, 'name' => 'Niue',  'code' => ''],
            ['id' => 166, 'name' => 'New Zealand',  'code' => ''],
            ['id' => 167, 'name' => 'Oman',  'code' => ''],
            ['id' => 168, 'name' => 'Panama',  'code' => ''],
            ['id' => 169, 'name' => 'Peru',  'code' => ''],
            ['id' => 170, 'name' => 'French Polynesia',  'code' => ''],
            ['id' => 171, 'name' => 'Papua New Guinea',  'code' => ''],
            ['id' => 172, 'name' => 'Philippines',  'code' => ''],
            ['id' => 173, 'name' => 'Pakistan',  'code' => ''],
            ['id' => 174, 'name' => 'Poland',  'code' => ''],
            ['id' => 175, 'name' => 'St. Pierre',  'code' => ''],
            ['id' => 176, 'name' => 'Pitcairn',  'code' => ''],
            ['id' => 177, 'name' => 'Puerto Rico',  'code' => ''],
            ['id' => 178, 'name' => 'Palestinian Territory',  'code' => ''],
            ['id' => 179, 'name' => 'Portugal',  'code' => ''],
            ['id' => 180, 'name' => 'Palau',  'code' => ''],
            ['id' => 181, 'name' => 'Paraguay',  'code' => ''],
            ['id' => 182, 'name' => 'Qatar',  'code' => ''],
            ['id' => 183, 'name' => 'Reunion',  'code' => ''],
            ['id' => 184, 'name' => 'Romania',  'code' => ''],
            ['id' => 185, 'name' => 'Russian Federation',  'code' => ''],
            ['id' => 186, 'name' => 'Rwanda',  'code' => ''],
            ['id' => 187, 'name' => 'Saudi Arabia',  'code' => ''],
            ['id' => 188, 'name' => 'Solomon Islands',  'code' => ''],
            ['id' => 189, 'name' => 'Seychelles',  'code' => ''],
            ['id' => 190, 'name' => 'Sudan',  'code' => ''],
            ['id' => 191, 'name' => 'Sweden',  'code' => ''],
            ['id' => 192, 'name' => 'Singapore',  'code' => ''],
            ['id' => 193, 'name' => 'St. Helena',  'code' => ''],
            ['id' => 194, 'name' => 'Slovenia',  'code' => ''],
            ['id' => 195, 'name' => 'Svalbard and Jan Mayen',  'code' => ''],
            ['id' => 196, 'name' => 'Slovakia',  'code' => ''],
            ['id' => 197, 'name' => 'Sierra Leone',  'code' => ''],
            ['id' => 198, 'name' => 'San Marino',  'code' => ''],
            ['id' => 199, 'name' => 'Senegal',  'code' => ''],
            ['id' => 200, 'name' => 'Somalia',  'code' => ''],
            ['id' => 201, 'name' => 'Suriname',  'code' => ''],
            ['id' => 202, 'name' => 'Sao Tome and Principe',  'code' => ''],
            ['id' => 203, 'name' => 'El Salvador',  'code' => ''],
            ['id' => 204, 'name' => 'Syrian Arab Republic',  'code' => ''],
            ['id' => 205, 'name' => 'Swaziland',  'code' => ''],
            ['id' => 206, 'name' => 'Turks and Caicos Islands',  'code' => ''],
            ['id' => 207, 'name' => 'Chad',  'code' => ''],
            ['id' => 208, 'name' => 'French Southern Territories',  'code' => ''],
            ['id' => 209, 'name' => 'Togo',  'code' => ''],
            ['id' => 210, 'name' => 'Thailand',  'code' => ''],
            ['id' => 211, 'name' => 'Tajikistan',  'code' => ''],
            ['id' => 212, 'name' => 'Tokelau',  'code' => ''],
            ['id' => 213, 'name' => 'Turkmenistan',  'code' => ''],
            ['id' => 214, 'name' => 'Tunisia',  'code' => ''],
            ['id' => 215, 'name' => 'Tonga',  'code' => ''],
            ['id' => 216, 'name' => 'Timor-Leste',  'code' => ''],
            ['id' => 217, 'name' => 'Turkey',  'code' => ''],
            ['id' => 218, 'name' => 'Trinidad and Tobago',  'code' => ''],
            ['id' => 219, 'name' => 'Tuvalu',  'code' => ''],
            ['id' => 220, 'name' => 'Taiwan',  'code' => ''],
            ['id' => 221, 'name' => 'Tanzania',  'code' => ''],
            ['id' => 222, 'name' => 'Ukraine',  'code' => ''],
            ['id' => 223, 'name' => 'Uganda',  'code' => ''],
            ['id' => 224, 'name' => 'US (Island)',  'code' => ''],
            ['id' => 225, 'name' => 'United States',  'code' => ''],
            ['id' => 226, 'name' => 'Uruguay',  'code' => ''],
            ['id' => 227, 'name' => 'Uzbekistan',  'code' => ''],
            ['id' => 228, 'name' => 'Holy See',  'code' => ''],
            ['id' => 229, 'name' => 'St. Vincent',  'code' => ''],
            ['id' => 230, 'name' => 'Venezuela',  'code' => ''],
            ['id' => 231, 'name' => 'Virgin Islands, British',  'code' => ''],
            ['id' => 232, 'name' => 'Virgin Islands, U.S.',  'code' => ''],
            ['id' => 233, 'name' => 'Vietnam',  'code' => ''],
            ['id' => 234, 'name' => 'Vanuatu',  'code' => ''],
            ['id' => 235, 'name' => 'Wallis and Futuna',  'code' => ''],
            ['id' => 236, 'name' => 'Samoa',  'code' => ''],
            ['id' => 237, 'name' => 'Yemen',  'code' => ''],
            ['id' => 238, 'name' => 'Mayotte',  'code' => ''],
            ['id' => 239, 'name' => 'Serbia',  'code' => ''],
            ['id' => 240, 'name' => 'South Africa',  'code' => ''],
            ['id' => 241, 'name' => 'Zambia',  'code' => ''],
            ['id' => 242, 'name' => 'Montenegro',  'code' => ''],
            ['id' => 243, 'name' => 'Zimbabwe',  'code' => ''],
            ['id' => 244, 'name' => 'Unknown',  'code' => ''],
            ['id' => 245, 'name' => 'Satellite Provider',  'code' => ''],
            ['id' => 246, 'name' => 'Other',  'code' => ''],
            ['id' => 247, 'name' => 'Aland Islands',  'code' => ''],
            ['id' => 248, 'name' => 'Guernsey',  'code' => ''],
            ['id' => 249, 'name' => 'Isle of Man',  'code' => ''],
            ['id' => 250, 'name' => 'Jersey',  'code' => ''],
            ['id' => 251, 'name' => 'St. Barthelemy',  'code' => ''],
            ['id' => 252, 'name' => 'Saint Martin', 'code' => '']]
        );
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('osu_country');
    }
}
