<?php

namespace App\Libraries;

class Packets
{
    const IN_SetUserState = 0;
    const IN_RecieveChatMSG = 1;
    const IN_Logout = 2;
    const IN_LocalUpdate = 3;
    const IN_KeepAlive = 4;
    const OUT_LoginRequest = 5;
    const OUT_Error = 6;
    const OUT_SendChatMSG = 7;
    const OUT_Ping = 8;
    const OUT_HandleIRCUsername = 9;
    const OUT_HandleIRCDisconnect = 10;
    const OUT_HandleStatsUpdate = 11;
    const OUT_HandleUserDisconnect = 12;
    const OUT_SpectatorJoin = 13;
    const OUT_SpectatorDisconnect = 14;
    const OUT_SpectatorFrames = 15;
    const IN_StartSpectating = 16;
    const IN_StopSpectating = 17;
    const IN_SpectatingData = 18;
    const OUT_UpdateClient = 19;
    const IN_Error = 20;
    const IN_SpectateFailed = 21;
    const OUT_SpectatorFailed = 22;
    const OUT_Popup = 23;
    const OUT_OrangeNotification = 24;
    const IN_ReceivePM = 25;
    const OUT_RoomUpdate = 26;
    const OUT_RoomNew = 27;
    const OUT_RoomDisband = 28;
    const IN_MPLeave = 29;
    const IN_MPJoin = 30;
    const IN_RoomCreate = 31;
    const IN_RoomJoin = 32;
    const IN_RoomLeave = 33;
    const UK0034 = 34; // Obsolete
    const UK0035 = 35; // Obsolete
    const OUT_RoomJoinSuccess = 36;
    const OUT_RoomJoinFailed = 37;
    const IN_RoomChangeSlot = 38;
    const IN_RoomReady = 39;
    const IN_RoomLock = 40;
    const IN_RoomChangeSettings = 41;
    const OUT_FSpectatorJoined = 42; // Friend?
    const OUT_FSpectatorLeft = 43; // Friend?
    const IN_RoomStart = 44;
    const RoomEveryoneLoaded = 45; // No one is missing a beatmap
    const OUT_RoomStart = 46;
    const IN_RoomScoreUpdate = 47;
    const OUT_RoomScoreUpdate = 48;
    const IN_RoomComplete = 49;
    const OUT_RoomHostTransferred = 50;
    const IN_RoomChangeMods = 51;
    const IN_RoomLoaded = 52; // You have the beatmap and you are ready
    const OUT_RoomEveryoneLoaded = 53; // Ask Peppy why there are duplicates
    const IN_RoomNoBeatmap = 54;
    const IN_RoomNotReady = 55;
    const IN_RoomFailed = 56;
    const OUT_RoomPlayerFailed = 57;
    const OUT_RoomComplete = 58;
    const IN_RoomHasBeatmap = 59;
    const IN_RoomSkipRequest = 60;
    const OUT_RoomSkipRequest = 61;
    const OUT_Unauthorized = 62;
    const IN_JoinChannel = 63;
    const OUT_ChannelJoined = 64;
    const OUT_ChannelList = 65;
    const OUT_ChannelDeny = 66; // Something to do with channels
    const OUT_ChannelAutoJoin = 67;
    const IN_BeatmapInformation = 68; // Something to do with Beatmaps
    const OUT_BeatmapInformation = 69;
    const IN_RoomTransferHost = 70;
    const OUT_UserGroup = 71;
    const OUT_UserFriends = 72;
    const IN_AddFriend = 73;
    const IN_RemoveFriend = 74;
    const OUT_Protocol = 75;
    const OUT_RoomTitleChange = 76;
    const IN_RoomChangeTeam = 77;
    const IN_LeaveChannel = 78;
    const IN_OnlinePlayers = 79;
    const OUT_Monitor = 80; // HoLLy-HaCKeR: Sneaky Shizzle
    const OUT_RoomPlayerSkipped = 81;
    const IN_IRCSetAwayMsg = 82;
    const OUT_PlayerLocaleInfo = 83;
    const IRCOnly = 84;
    const IN_OnlineStats = 85;
    const OUT_Restart = 86;
    const IN_RoomInvite = 87;
    const OUT_RoomInvite = 88;
    const OUT_ChannelsLoaded = 89;
    const IN_RoomChangePassword = 90;
    const OUT_RoomChangePassword = 91;
    const OUT_BanStatus = 92;
    const IN_TournyRoomInfoRequest = 93;
    const OUT_UserSilenced = 94;
    const OUT_OnlineSingle = 95;
    const OUT_OnlineList = 96;
    const IN_UserInfoRequest = 97;
    const IN_UserInfoRequestAll = 98;
    const IN_BlockUserPM = 99;
    const OUT_BlockUserPM = 100;
    const OUT_TargetSilenced = 101;
    const OUT_ForceUpdate = 102;
    const OUT_SwitchServer = 103;
    const OUT_Restricted = 104;
    const OUT_BlackScreenNotification = 105;
    const IN_RoomAbort = 106;
    const OUT_SwitchTournyServer = 107;
    const IN_TournyRoomJoinChannel = 108;
    const IN_TournyRoomLeaveChannel = 109;
}
